<?php

namespace Database\Seeders;

use App\Models\Dataset;
use Illuminate\Database\QueryException;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Process;

class DatasetSeeder extends Seeder
{
    /**
     * Reads the datasets from the CSV generated by nhanes_utils and populates the database
     */
    public function run(): void
    {
        $lines = array_map('str_getcsv', file(storage_path('app/nhanes_datasets.csv')));
        $data = array_slice($lines, 1); // Exclude headers

        foreach ($data as $dataset) {
            $model = new Dataset([
                'start_year' => explode('-', $dataset[0])[0],
                'end_year' => explode('-', $dataset[0])[1],
                'component' => $dataset[1],
                'description' => $dataset[2],
                'docs_url' => $dataset[3],
                'data_url' => $dataset[4],
            ]);

            // If dataset with data_url already exists, continue
            if (Dataset::query()->where('data_url', $model->data_url)->exists()) {
                continue;
            }

            // Otherwise, save the model
            $model->save();
        }
    }
}
